name: verified-examples
on: [push, pull_request]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.email ci@ci && git config --global user.name ci
      - uses: DrVelvetFog/verified-examples@v1
